import type {
  Agent,
  Approval,
  AuditEvent,
  Integration,
  Policy,
} from "./types";

export const agents: Agent[] = [
  {
    id: "agent-support",
    name: "Support Resolution Agent",
    description: "Resolves common support issues and updates customer tickets.",
    owner: "Sam Ortega",
    team: "SecOps",
    status: "healthy",
    provider: "OpenAI",
    permissions: ["Tickets: read", "Tickets: write", "Knowledge: read"],
    actions: 1248,
    cost: 2143.21,
    lastAction: "Resolved ticket #84217",
    lastSeen: "12 sec ago",
  },
  {
    id: "agent-finance",
    name: "Finance Reconciliation",
    description: "Matches ledger entries and flags anomalies for review.",
    owner: "Aisha Lin",
    team: "Finance",
    status: "review",
    provider: "Anthropic",
    permissions: ["Ledger: read", "Exports: request"],
    actions: 642,
    cost: 1842.77,
    lastAction: "Requested Q2 data export",
    lastSeen: "2 min ago",
  },
  {
    id: "agent-release",
    name: "GitHub Release Assistant",
    description: "Prepares release notes and guarded production releases.",
    owner: "Jordan Malik",
    team: "Platform Eng",
    status: "blocked",
    provider: "OpenAI",
    permissions: ["Repos: read", "Releases: write", "Actions: trigger"],
    actions: 315,
    cost: 1356.4,
    lastAction: "Release creation blocked",
    lastSeen: "4 min ago",
  },
  {
    id: "agent-contract",
    name: "Contract Review Agent",
    description: "Reviews standard contracts against approved legal playbooks.",
    owner: "Nina Park",
    team: "Legal",
    status: "healthy",
    provider: "Google",
    permissions: ["Contracts: read", "Comments: write"],
    actions: 228,
    cost: 987.12,
    lastAction: "Reviewed contract NDA-119",
    lastSeen: "8 min ago",
  },
  {
    id: "agent-marketing",
    name: "Marketing Insights Agent",
    description: "Produces weekly campaign insights from approved datasets.",
    owner: "Riley Kim",
    team: "Marketing",
    status: "healthy",
    provider: "OpenAI",
    permissions: ["Analytics: read", "Reports: write"],
    actions: 186,
    cost: 654.83,
    lastAction: "Generated weekly report",
    lastSeen: "14 min ago",
  },
];

export const approvals: Approval[] = [
  {
    id: "apr-release",
    agentId: "agent-release",
    agentName: "GitHub Release Assistant",
    request: "Create release v2.4.1",
    resource: "sentinelops/platform",
    context: "Creates a signed release and publishes build assets.",
    risk: "high",
    requestedBy: "Jordan Malik",
    requestedAt: "10:24 AM",
    status: "pending",
  },
  {
    id: "apr-finance",
    agentId: "agent-finance",
    agentName: "Finance Reconciliation",
    request: "Export financial data",
    resource: "Q2_Financials_2026",
    context: "Exports 14,820 rows to the approved finance S3 bucket.",
    risk: "medium",
    requestedBy: "Aisha Lin",
    requestedAt: "10:20 AM",
    status: "pending",
  },
  {
    id: "apr-support",
    agentId: "agent-support",
    agentName: "Support Resolution Agent",
    request: "Access sensitive tickets",
    resource: "127 customer tickets",
    context: "Bulk reads tickets containing payment-dispute metadata.",
    risk: "high",
    requestedBy: "Sam Ortega",
    requestedAt: "10:16 AM",
    status: "pending",
  },
  {
    id: "apr-contract",
    agentId: "agent-contract",
    agentName: "Contract Review Agent",
    request: "Share redlined agreement",
    resource: "MSA-2048",
    context: "Shares a redlined agreement with an external counterparty.",
    risk: "medium",
    requestedBy: "Nina Park",
    requestedAt: "10:08 AM",
    status: "pending",
  },
  {
    id: "apr-marketing",
    agentId: "agent-marketing",
    agentName: "Marketing Insights Agent",
    request: "Publish campaign report",
    resource: "FY26_Q3_Pipeline",
    context: "Publishes a report containing account-level pipeline data.",
    risk: "medium",
    requestedBy: "Riley Kim",
    requestedAt: "9:54 AM",
    status: "pending",
  },
  {
    id: "apr-support-refund",
    agentId: "agent-support",
    agentName: "Support Resolution Agent",
    request: "Issue customer refund",
    resource: "Order #49281",
    context: "Issues a $480 refund outside the agent's standard threshold.",
    risk: "high",
    requestedBy: "Sam Ortega",
    requestedAt: "9:41 AM",
    status: "pending",
  },
  {
    id: "apr-finance-write",
    agentId: "agent-finance",
    agentName: "Finance Reconciliation",
    request: "Post ledger adjustment",
    resource: "Ledger entry #88104",
    context: "Posts a reconciliation adjustment to the production ledger.",
    risk: "high",
    requestedBy: "Aisha Lin",
    requestedAt: "9:32 AM",
    status: "pending",
  },
];

export const policies: Policy[] = [
  {
    id: "pol-1",
    name: "Block exports to unapproved destinations",
    description: "Blocks bulk exports when the target destination is not approved.",
    scope: "All production agents",
    mode: "Block",
    effect: "block",
    priority: 10,
    enabled: true,
    matches: 12,
    activeVersionNumber: 1,
    latestVersionNumber: 1,
    activationStatus: "active",
    conditions: [
      { field: "action", operator: "eq", value: "data.export" },
      { field: "context.destinationApproved", operator: "eq", value: false },
    ],
  },
  {
    id: "pol-2",
    name: "Production changes require approval",
    description: "Requires a platform owner to approve production deployments and releases.",
    scope: "Engineering agents",
    mode: "Approval",
    effect: "approval",
    priority: 20,
    enabled: true,
    matches: 31,
    activeVersionNumber: 1,
    latestVersionNumber: 1,
    activationStatus: "active",
    conditions: [
      { field: "environment", operator: "eq", value: "production" },
      { field: "action", operator: "in", value: ["deploy.release", "github.release.create"] },
    ],
  },
  {
    id: "pol-3",
    name: "Large financial exports require approval",
    description: "Routes financial exports of at least 1,000 records to a human reviewer.",
    scope: "Finance agents",
    mode: "Approval",
    effect: "approval",
    priority: 30,
    enabled: true,
    matches: 8,
    activeVersionNumber: 1,
    latestVersionNumber: 1,
    activationStatus: "active",
    conditions: [
      { field: "action", operator: "eq", value: "data.export" },
      { field: "context.recordCount", operator: "gte", value: 1000 },
    ],
  },
];

const _demoNow = Date.now();
const _daysAgo = (days: number, hours = 10, minutes = 15) => {
  const d = new Date(_demoNow - days * 86400 * 1000);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
};
const _hoursAgo = (hours: number, minutes = 20) => {
  const d = new Date(_demoNow - hours * 3600 * 1000 - minutes * 60 * 1000);
  return d.toISOString();
};

export const auditEvents: AuditEvent[] = [
  {
    id: "evt-1",
    time: _hoursAgo(1, 12),
    agent: "GitHub Release Assistant",
    action: "Create GitHub release v2.4.1",
    result: "Blocked",
    actor: "Policy engine",
    detail: "Production change requires approval",
  },
  {
    id: "evt-2",
    time: _hoursAgo(2, 45),
    agent: "Finance Reconciliation",
    action: "Export financial dataset",
    result: "Approved",
    actor: "Aisha Lin",
    detail: "Routed to approval queue",
  },
  {
    id: "evt-3",
    time: _hoursAgo(4, 18),
    agent: "PII Data Handling",
    action: "Policy configuration updated",
    result: "Allowed",
    actor: "Maya Patel",
    detail: "Added customer payment metadata",
  },
  {
    id: "evt-4",
    time: _hoursAgo(8, 30),
    agent: "Contract Review Agent",
    action: "Read contract NDA-119",
    result: "Allowed",
    actor: "Policy engine",
    detail: "Within approved legal workspace",
  },
  {
    id: "evt-5",
    time: _hoursAgo(14, 50),
    agent: "Support Resolution Agent",
    action: "Bulk read sensitive tickets",
    result: "Blocked",
    actor: "Policy engine",
    detail: "Privilege boundary exceeded",
  },
  {
    id: "evt-6",
    time: _daysAgo(2, 14, 30),
    agent: "GitHub Release Assistant",
    action: "Deploy canary release v2.4.0",
    result: "Approved",
    actor: "Jordan Malik",
    detail: "Four-eyes quorum reached",
  },
  {
    id: "evt-7",
    time: _daysAgo(3, 9, 15),
    agent: "Finance Reconciliation",
    action: "Sync Q2 ledger transactions",
    result: "Allowed",
    actor: "Policy engine",
    detail: "Standard scheduled reconciliation",
  },
  {
    id: "evt-8",
    time: _daysAgo(5, 16, 45),
    agent: "Security Guard",
    action: "operator.login_attempt",
    result: "Allowed",
    actor: "Sam Ortega",
    detail: "MFA challenge verified successfully",
  },
  {
    id: "evt-9",
    time: _daysAgo(10, 11, 20),
    agent: "Contract Review Agent",
    action: "Export vendor redlines",
    result: "Approved",
    actor: "Nina Park",
    detail: "Legal counsel sign-off",
  },
  {
    id: "evt-10",
    time: _daysAgo(18, 13, 10),
    agent: "Support Resolution Agent",
    action: "Mass refund processing",
    result: "Blocked",
    actor: "Policy engine",
    detail: "Threshold exceeded ($10,000 safety limit)",
  },
  {
    id: "evt-11",
    time: _daysAgo(35, 10, 0),
    agent: "Platform Operations",
    action: "api_key.create",
    result: "Allowed",
    actor: "Admin",
    detail: "Production agent token issued",
  },
];

export const integrations: Integration[] = [
  {
    id: "int-github",
    name: "GitHub",
    description: "Observe repository actions and enforce guarded releases.",
    connected: true,
    category: "Engineering",
    events: "12.4k events",
  },
  {
    id: "int-slack",
    name: "Slack",
    description: "Route approvals and send high-risk activity alerts.",
    connected: true,
    category: "Communication",
    events: "1.8k events",
  },
  {
    id: "int-https-webhooks",
    name: "HTTPS Webhooks",
    description: "Push signed governance and security events to SIEM or SOAR endpoints.",
    connected: true,
    category: "SIEM & Webhooks",
    events: "2 destinations configured",
    status: "configured",
    mode: "HMAC-SHA256 Signed",
  },
  {
    id: "int-salesforce",
    name: "Salesforce",
    description: "Monitor agent access to customer and account records.",
    connected: true,
    category: "Customer data",
    events: "8.2k events",
  },
  {
    id: "int-microsoft",
    name: "Microsoft 365",
    description: "Apply policy to documents, email, and collaboration data.",
    connected: false,
    category: "Productivity",
    events: "Not connected",
  },
  {
    id: "int-jira",
    name: "Jira",
    description: "Track autonomous ticket updates and workflow transitions.",
    connected: false,
    category: "Engineering",
    events: "Not connected",
  },
  {
    id: "int-aws",
    name: "AWS",
    description: "Govern agent access to cloud resources and sensitive datasets.",
    connected: false,
    category: "Infrastructure",
    events: "Not connected",
  },
  {
    id: "int-python-sdk",
    name: "Python SDK",
    description: "Connect Python-based autonomous AI agents with native decorator guards.",
    connected: true,
    category: "Agent SDK",
    events: "Active client",
    status: "configured",
    mode: "Evaluation & Guarding",
    url: "/docs/PYTHON_INTEGRATION.md",
  },
];

export const chartData = [
  { day: "Mon", allowed: 680, approved: 278, blocked: 64 },
  { day: "Tue", allowed: 726, approved: 316, blocked: 82 },
  { day: "Wed", allowed: 828, approved: 408, blocked: 96 },
  { day: "Thu", allowed: 876, approved: 452, blocked: 112 },
  { day: "Fri", allowed: 824, approved: 408, blocked: 98 },
  { day: "Sat", allowed: 842, approved: 426, blocked: 83 },
  { day: "Sun", allowed: 871, approved: 454, blocked: 103 },
];
