import { PublicDocument } from "@/components/public-document";

export default function TermsPage() {
  return <PublicDocument title="Terms of service" updated="October 8, 2026" intro="These terms apply to SentinelOps, an AI-agent governance service operated by Dibyan Maharjan, a sole proprietor in Nepal (“SentinelOps,” “we,” or “us”), through sentinelops-ai.com (the “Service”). By creating an account, starting a trial, or using a paid plan, you agree to these terms. If you are accepting for an organization, you confirm you have authority to bind it." sections={[
    { title: "The Service and your responsibilities", body: "SentinelOps provides tools to configure governance policies, review and approve agent actions, manage integrations, and retain audit evidence. You are responsible for your account, your agents and connected systems, the instructions and data you submit, and deciding whether to approve an action. Keep credentials secure and maintain independent safeguards for critical operations. The Service is not a guarantee that an AI agent or connected system will behave safely or correctly." },
    { title: "Accounts and acceptable use", body: "Provide accurate account information and limit access to authorized users. Do not use the Service unlawfully, interfere with its operation, bypass security controls, access another customer's data, or submit data you are not authorized to process. We may suspend access where reasonably necessary to protect users, the Service, or comply with law." },
    { title: "Plans, trials, and renewal", body: "Plan features and current prices are shown on the pricing page and at checkout. Plans may be offered monthly or annually and currently include a 7-day trial where shown. Unless checkout says otherwise, a subscription converts to its selected paid plan at the end of the trial and renews for successive billing periods until canceled. Paddle processes checkout and subscription billing as our authorized merchant of record. Taxes, currency, and the final amount are shown by Paddle at checkout. You authorize recurring charges to your selected payment method until cancellation." },
    { title: "Cancellation, refunds, and consumer rights", body: "You can manage or cancel an eligible subscription through the account billing portal. Unless Paddle checkout or applicable law provides otherwise, cancellation takes effect at the end of the current billing period; access remains until then. Trial cancellation must be completed before the trial converts to a paid subscription to avoid the first recurring charge. Refund requests are handled under Paddle's buyer refund policy and applicable law; details are on our Refund & Cancellation Policy page. Nothing in these terms limits rights that cannot legally be waived." },
    { title: "Availability, changes, and termination", body: "We may update or discontinue features and will take reasonable steps to communicate material changes. The Service is provided without a guaranteed uptime commitment unless we separately agree otherwise in writing. Either party may stop using or providing the Service. We may suspend or terminate access for a material breach, security risk, or legal requirement. Terms that by their nature should continue, including accrued payment obligations and liability provisions, survive termination." },
    { title: "Intellectual property, privacy, and contact", body: "We retain rights in the Service; you retain rights in the content and data you submit and grant us the limited rights needed to operate the Service. Our Privacy Notice explains personal-data handling. To the extent permitted by law, these terms are governed by the laws of Nepal, without limiting mandatory consumer protections that apply where you live. Questions: cs@sentinelops-ai.com." },
  ]} />;
}
