import { PublicDocument } from "@/components/public-document";

export default function TermsPage() {
  return <PublicDocument title="Terms of service" updated="October 9, 2026" intro="These terms apply to SentinelOps, an AI-agent governance service operated by Dibyan Maharjan, a sole proprietor in Nepal (“SentinelOps,” “we,” or “us”), through sentinelops-ai.com (the “Service”). By creating an account or using the Service, you agree to these terms. If you are accepting for an organization, you confirm you have authority to bind it." sections={[
    { title: "The Service and your responsibilities", body: "SentinelOps provides tools to configure governance policies, review and approve agent actions, manage integrations, and retain audit evidence. You are responsible for your account, your agents and connected systems, the instructions and data you submit, and deciding whether to approve an action. Keep credentials secure and maintain independent safeguards for critical operations. The Service is not a guarantee that an AI agent or connected system will behave safely or correctly." },
    { title: "Accounts and acceptable use", body: "Provide accurate account information and limit access to authorized users. Do not use the Service unlawfully, interfere with its operation, bypass security controls, access another customer's data, or submit data you are not authorized to process. We may suspend access where reasonably necessary to protect users, the Service, or comply with law." },
    { title: "Free pilot and future plans", body: "The Pilot workspace is currently available at no charge with the limits shown on the pricing page. Starter, Pro, and Advanced are planned offerings and are not currently available to purchase. We may change the pilot, planned features, or availability as the Service develops. If paid plans become available, their price, billing interval, trial terms, taxes, and renewal conditions will be shown before purchase and in the applicable checkout flow. No paid subscription or recurring payment is created by signing up for the free pilot." },
    { title: "Existing subscriptions, cancellation, and consumer rights", body: "If you already have a paid subscription, the terms and cancellation conditions presented when you subscribed continue to apply to that subscription. You can manage an eligible existing subscription through the billing portal or contact cs@sentinelops-ai.com for help. Refund requests are handled under the applicable purchase terms, Paddle's buyer refund policy where relevant, and applicable law. Nothing in these terms limits rights that cannot legally be waived." },
    { title: "Availability, changes, and termination", body: "We may update or discontinue features and will take reasonable steps to communicate material changes. The Service is provided without a guaranteed uptime commitment unless we separately agree otherwise in writing. Either party may stop using or providing the Service. We may suspend or terminate access for a material breach, security risk, or legal requirement. Terms that by their nature should continue, including accrued payment obligations and liability provisions, survive termination." },
    { title: "Intellectual property, privacy, and contact", body: "We retain rights in the Service; you retain rights in the content and data you submit and grant us the limited rights needed to operate the Service. Our Privacy Notice explains personal-data handling. To the extent permitted by law, these terms are governed by the laws of Nepal, without limiting mandatory consumer protections that apply where you live. Questions: cs@sentinelops-ai.com." },
  ]} />;
}
