import { PublicDocument } from "@/components/public-document";

export default function PrivacyPage() {
  return <PublicDocument title="Privacy notice" updated="October 6, 2026" intro="This notice describes how SentinelOps handles information when you visit sentinelops-ai.com, create a workspace, or use the Service." sections={[
    { title: "Information we process", body: "Depending on how you use the Service, we process contact and account details; organization and workspace settings; agent, policy, approval, integration, and audit records; support correspondence; and basic technical and security data such as logs and request metadata. When you subscribe, we receive billing and subscription references such as Paddle customer, transaction, and subscription IDs, plan, and status. Payment card details are collected and handled by Paddle, not stored in SentinelOps application tables." },
    { title: "Purposes and sharing", body: "We use information to provide and secure the Service, enforce configured governance workflows, manage accounts and subscriptions, respond to support requests, prevent abuse, and meet legal obligations. We do not sell personal information. We share information with service providers that help operate the Service, including hosting, database, email, and Paddle for checkout and billing, and where required by law or to protect rights and safety. Providers process information under their own terms and applicable arrangements." },
    { title: "Retention and security", body: "We retain information for as long as needed to provide the Service and for legitimate operational, security, dispute-resolution, and legal purposes. Audit retention may depend on the plan and workspace configuration. We use access controls and security measures designed to protect customer information; no internet service can promise absolute security." },
    { title: "Your choices and contact", body: "Depending on your location, you may have rights to request access, correction, deletion, or a copy of your personal information, subject to applicable law. Workspace administrators can manage user access and contact us for requests. Contact cs@sentinelops-ai.com. We may need to verify your request and retain certain records where legally required or necessary to protect the Service." },
    { title: "International processing and updates", body: "The Service and its providers may process information in countries other than where you live. Where required, appropriate safeguards will be used. We may update this notice as the Service changes; the date above shows when it was last revised. Material changes will be communicated through the Service or another reasonable channel." },
  ]} />;
}
